default:
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind

before_script:
  - docker info
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin

stages:
  - build
  - test
  - release
  - deploy

build:
  stage: build
  tags:
    - docker
    - deploy
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

test:
  stage: test
  tags:
    - docker
    - deploy
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker run $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG echo "Running dummy tests"

release:
  stage: release
  tags:
    - docker
    - deploy
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE:release
    - docker push $CI_REGISTRY_IMAGE:release
  only:
    - main

deploy:
  stage: deploy
  tags:
    - docker
    - deploy
  image: jenkins/ssh-slave
  before_script:
    - echo -n $SSH_PRIVATE_KEY | base64 -d > SSH_KEY_FILE
    - chmod 400 SSH_KEY_FILE
  script:
    - ssh -i SSH_KEY_FILE -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH; docker-compose pull && docker-compose up -d"
  environment: 
    name: production
  only:
    - main
