apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: josephumt/chatops:kube
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: flask-config
        - secretRef:
            name: flask-secrets
